rlbench:
    task:  open_drawer   
    demos: 30

    demo_path: /home/cjz/OTA/ota_data/     
    episode_length: 10  
    cameras: [active]  
    camera_resolution: [128, 128]  
    scene_bounds: [-0.5, -0.5, -0.15, 0.5, 0.5, 0.85] 
replay:
    batch_size: 64 #68
    timesteps: 1
    prioritisation: True     
    use_disk: True
    path: /home/cjz/OTA/ota_data/replay  # Only used when use_disk is True.

framework:
    log_freq: 100
    save_freq: 100
    train_envs: 0
    eval_envs: 1
    replay_ratio: 128 # 32
    transitions_before_train: 200
    tensorboard_logging: True
    csv_logging: True
    training_iterations: 0
    gpu: 0
    env_gpu: 0
    logdir: /home/cjz/OTA/ota_data/train/  
    seeds: 1
    setseeds: []

defaults:
    - method: OTA # OTA   C2FARM   

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task}/${method.name}
